version: '3.7'

services:
  web:
    image: my_flask_app:latest
    command: python app.py
    ports:
      - "5003:5003"
    volumes:
      - ./charades_app:/app/charades_app  # This mounts the 'charades_app' directory
