version: '3.7'

services:
  web:
    image: vithushar/charades:v1.1
    ports:
      - "5003:5003"
    environment: 
      SECRET_KEY: mysecret
      DATABASE_URL: postgresql://username:password@postgres:5432/db
  
  db:
    image: postgres:latest
    environment: 
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db 
